### ISSUE TITLE
Special characters removed

### ISSUE THREAD

**Issue by davenlin19** [pavelvlasov/mongoose-search-plugin#6]
Hi,

I have a problem with some words in French. For exemple: "récépissé" which is transformed to "piss". So "ré", "cé" and the last character "é" are being removed.

Do you have an option to resolve this problem ?

Thanks !

**Comment by pavelvlasov** [comment]
@davenlin19 it's not related to the plugin itself, you should take a look at https://github.com/NaturalNode/natural tokenizer options.
